# Generated by Django 5.1.4 on 2024-12-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_generatedpropertysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratePropertyRatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField()),
            ],
        ),
    ]
